### ISSUE TITLE
Can you publish a wheel?

### ISSUE THREAD

**Issue by matthewdeanmartin** [ravener/stopwatch.py#2]
As a security measure, more orgs are mandating `export PIP_ONLY_BINARY=:all:` so that only wheels are installed (sdist runs setup.py with arbitrary code in on install).

Can you add a wheel on pypi so this can be used in more locked down environments?

`python setup.py build sdist bdist_wheel` creates the wheel, `twine upload dist/*` uploads it.

Here are more details on how to [build/publish a wheel](https://realpython.com/python-wheels/#building-a-pure-python-wheel).

I'd offer a PR, but the person who controls the pypi page needs to do the upload part.

**Comment by ravener** [comment]
hi @matthewdeanmartin I apologize for the extremely late response but for some reason I did not get notified of this issue.

I've recently found some motivation to clean up this project, added support for changing the decimal precision and a whole lot of cleanup, the latest version `1.1.0` comes with wheels uploaded.
